version: '3.8'

services:
  main:
    image: 412530390400.dkr.ecr.ap-northeast-2.amazonaws.com/cmsn-scrap-browser:latest
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
      - "9222:9222"
      - "18081:18081"