version: "3"
services:
  app:
    image: cmsn-scrap-go:latest
    container_name: cmsn-scrap-go
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18081:18081"
    volumes:
      - ./app:/app
