name: Run Tests

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: >-
          --shm-size 2g
        ports:
          - 4444:4444

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest selenium flask-testing

    - name: Run tests
      env:
        SELENIUM_URL: http://localhost:4444/wd/hub  # Selenium server URL
      run: |
        pytest test_scraper.py
